### ISSUE TITLE
Decide v1's testing strategy and the hardware smoke checklist

### ISSUE THREAD

**Issue by SamuelColacchia** [SamuelColacchia/freedomfrom#19]
Part of #1

## Question

The map held testing as fog. Half of it was already sharp: `FreedomFromKit` (ADR 0002) fixes what is unit-testable headless — deadline reconciliation, ADR 0004's walk-forward step calculation, clamping an interval into the legal 15-minute-to-1-week window, degrade-on-unresolvable-token, and now ADR 0005's coverage computation. The dim half was the manual one, and five ADRs have since accumulated a specific list of things only a paired device can answer.

What remains to decide:

- **What `FreedomFromKit`'s test surface actually is**, and whether those tests are the contract the build is written against or a safety net added after. It is the only thing testable with zero hardware, which matters disproportionately while hardware access is still zero.
- **The ordered manual smoke checklist** — what a human with a paired iPhone runs, in what order, and what each check proves. The accumulated items:
  - the Keychain access group being readable from an extension (ADR 0002)
  - `ShieldConfig` mutating a `ManagedSettingsStore` from inside its memory budget — load-bearing twice, for ADR 0004's third reconciliation point and ADR 0005's self-shield fix
  - whether an unresolvable token is detectable at all, which the whole degradation path assumes (ADR 0002, ADR 0005)
  - whether `denyAppRemoval` and `requireAutomaticDateAndTime` bite under `.individual` (ADR 0001)
  - whether `requestAuthorization` re-prompts from a `.denied` status (ADR 0005)
  - web-block coverage per browser — Safari, Chrome, Firefox, Brave, in-app `WKWebView`, all undocumented — and whether a never-visited site can be picked cold (#15)
- **Which checks gate TestFlight, and which amendment fires when one fails.** Several ADRs already name their own fallback: ADR 0004 holds a local notification in reserve, ADR 0005 falls back to simply accepting a self-shield. The checklist has to bind each failure to its amendment, or the first red result reopens a decision instead of triggering one.
- **Whether anything runs automated on device at all**, or the device half is manual by definition.

**Resolution.** A checked-in checklist a human can run top to bottom, plus an ADR if the test-seam decision turns out to be a real trade-off rather than a restatement of ADR 0002. Use `/grilling` and `/domain-modeling`.

**Comment by SamuelColacchia** [comment]
**Testing splits along the line the SDK draws, and the line is not where ADR 0002 assumed.**

## The boundary is forced

A probe of the build host turned ADR 0002's aspiration into a constraint with a hard edge. `swift test` works fine on the Mac (Swift 6.3.3, ~9s cold), but a package compiled for the macOS host may name almost nothing from the Screen Time stack:

- `FamilyActivitySelection` is **absent from the macOS module entirely** — `cannot find type in scope`, not merely unavailable.
- `ApplicationToken`, `WebDomainToken`, `Token<T>`, `Application`, `ManagedSettingsStore`, `DeviceActivitySchedule`, `DeviceActivityName`, `DeviceActivityCenter`, `AuthorizationCenter`, `AuthorizationStatus` are all declared but `@available(macOS, unavailable)`.
- `ManagedSettingsUI` is not in the native macOS SDK at all — Catalyst slice only.
- Bare `import FamilyControls` / `ManagedSettings` / `DeviceActivity` compiles at exit 0. Importing is free; *using* is impossible.
- The one exception: `FamilyControlsError` compiles once the package declares `platforms: [.macOS(.v13)]`.

There is an escape hatch and it was rejected: an **iOS 26.5 Simulator runtime is installed** (11 devices), every one of those types typechecks clean for `arm64-apple-ios26.0-simulator`, and the simulator platform sets `CODE_SIGNING_ALLOWED = NO` — so Simulator tests would need no signing and could run today. But it buys the ability to *name* those types, not to *construct* them: `Token`'s only public initializer is `init(from decoder:)`, so no test can mint an `ApplicationToken` without a blob captured from a real device. The blocker is hardware, and the Simulator supplies none of it.

**So `FreedomFromKit` imports no Apple framework at all.** What crosses the seam is opaque handles, counts, and dates; the app owns every conversion to and from a `FamilyActivitySelection`. Coverage becomes a set difference and a flag, which is what ADR 0005 described in prose. This makes ADR 0002's claim true rather than aspirational, and keeps a nine-second loop.

## Its tests are the contract, not a net

The build spec ships them as named cases written *before* their implementations, across seven areas: deadline reconciliation, the walk-forward step, the clamps, coverage and degradation, domain canonicalization and the 50 rule, the draft, and the three-value outcome vocabulary. Every one is transcription of a rule an ADR already fixed. With no paired device these are the only executable feedback in the project, and tests written afterwards get written to match the code — with nothing else here able to catch that.

## The device half is manual, and walked in a fixed order

**Two checks can block**, because they change the architecture when red, so they run on a **walking skeleton** — the real three targets with real bundle IDs and entitlements, doing nothing but authorizing, picking, storing, shielding, and letting the extensions read. Kept, not thrown away: it is v1's first work item, it is the first thing to exercise the whole headless build-sign-install chain, and it is built **for the Simulator first** so that a failure there is a code failure rather than a signing one.

- Keychain access group readable from an extension → red re-adds the App Group ADR 0002 removed.
- `ShieldConfig` mutating a `ManagedSettingsStore` → red drops ADR 0004's third reconciliation point for its deferred notification, and ADR 0005's self-shield fix for accepting a self-shield.

**Everything else is observed across two commitments**, one clean and one sacrificial, because revoking, deleting, and forcing token churn each mark a commitment broken and a broken commitment contaminates every later observation of a clean one. Roughly 40 minutes, most of it waiting. One ordering is forced by the design itself: **revoke before deleting**, because a working `denyAppRemoval` prevents deleting the app.

Each check names its amendment before it runs, so a red result triggers a decision instead of reopening one. Most amendments already existed in ADR prose; this collects them.

## Evidence is a sysdiagnose, because `log stream --device` is gone

Removed in macOS 26.6 — `log --help` has no mention of a device, and `devicectl` (v518.33) has no log or console subcommand anywhere in its tree. `devicectl device process launch --console` streams stdout/stderr only for a process devicectl launched, which is the app and never the two extensions, and the extensions are precisely what the structural checks are about.

So the record is `devicectl device sysdiagnose` plus `log show --archive --predicate 'subsystem == "com.samuelcolacchia.freedomfrom"'` on the Mac; Console.app is an optional live view. That makes the logging contract load-bearing: **permanent in release**, one category per process, structural facts `.public` (record read, mutation landed, resolved-of-named counts, deadline, window registered, release lateness, break and degrade marks), and **target identities never logged at all** — no bundle IDs, no tokens, no domain strings. Default redaction would print `<private>` for every value, and a coverage count of 2-of-3 *is* the observation. This gives the app no voice: a log is not a screen.

## What gates a TestFlight invite

Not a green checklist — all-green would deadlock on questions nobody can answer, like what Brave does with a `.specific` filter. The gate is that **both runs have happened and the app's claims have been reconciled against what they showed**; a red result changes what the app says, not whether it ships. This bites hardest on one check: ADR 0003 rests all of informed consent on a single first-run sentence, so if `denyAppRemoval` silently no-ops under `.individual`, that sentence claims a restriction that does not exist — a known unknown for the dev, a false claim for a stranger.

## Two adjustments to the accumulated list

- **One check dropped as obsolete.** "Can a never-visited site be picked cold" came from #15, but ADR 0006 chose typed domains over picker tokens, so nothing in v1 picks a site.
- **One check moved earlier than its bucket suggests.** Whether a `FamilyActivitySelection` decoded from the Keychain hands back to `FamilyActivityPicker` with its apps checked is observed on the skeleton. It cannot block a build, but its red result *deletes* a decided behaviour (ADR 0008's draft would keep only domains and length), and the skeleton needs the picker anyway to have a token to shield.

## Artifacts

- ADR `docs/adr/0009-a-foundation-only-kit-and-a-hardware-pass-a-human-walks.md`
- Checklist `docs/hardware-smoke-checklist.md` — 17 checks in four phases, each with its amendment, plus a results table to fill in and commit
- No new `CONTEXT.md` terms: structural gate, claim-filler, and walking skeleton are process vocabulary, and the glossary is domain-only
